package corbaBanque;


/**
* corbaBanque/IBanqueRemoteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banque.idl
* mercredi 20 janvier 2021 13 h 42 WEST
*/

public interface IBanqueRemoteOperations 
{
  double conversion (double mt);
  corbaBanque.Compte getCompte (int code);
  corbaBanque.Compte[] getComptes ();
} // interface IBanqueRemoteOperations
